Repository Tzahi12345/YoutubeDL-Material, pull requests merged in 2022-05, with the labels that each got.

#577 Dockerfile uses Ubuntu 20.04, fix obtain ffmpeg
  Dockerfile
  docker-build.sh
Labels: is: bug, is: enhancement, DEPENDENCIES/DISTRIBUTION

#582 fix docker-build.sh for ubuntu, what a ride
  docker-build.sh
Labels: is: bug, DEPENDENCIES/DISTRIBUTION

#590 Adding ignore parameters to docker build-and-push
  .github/workflows/docker.yml
Labels: is: enhancement, DEPENDENCIES/DISTRIBUTION

#595 Permissions fixes
  Dockerfile
Labels: is: bug, FILE MANAGEMENT

#598 Fixing Ubuntu-introduced issues and further improvements
  .github/workflows/docker.yml
  Dockerfile
  backend/entrypoint.sh
  backend/fix-scripts/001-fix_download_permissions.sh
Labels: is: bug, is: enhancement, meta: help wanted, DEPENDENCIES/DISTRIBUTION, meta: update docs

#602 Various bug fixes and heroku improvements
  Dockerfile
  Dockerfile.heroku
  Procfile
  app.json
  backend/app.js
  backend/consts.js
  backend/db.js
  backend/downloader.js
  backend/test/tests.js
  backend/utils.js
  backend/youtube-dl.js
  chrome-extension.pem
  heroku.yml
  package.json
  src/app/subscriptions/subscriptions.component.html
  src/assets/i18n/messages.en.xlf
  youtubedl-material-chrome-extension.crx
Labels: is: bug, is: enhancement, DEPENDENCIES/DISTRIBUTION, UI, DATABASE

#619 Autoclose stale issues lacking requested response
  .github/workflows/close-issue-if-noresponse.yml
Labels: is: enhancement
