Repository Tzahi12345/YoutubeDL-Material, pull requests merged in 2022-06, with the labels that each got.

#628 add fonts and css local for better privacy
  src/bootstrap.min.css
  src/fonts/KFOmCnqEu92Fr1Mu4WxKOzY.woff2
  src/fonts/KFOmCnqEu92Fr1Mu4mxK.woff2
  src/fonts/KFOmCnqEu92Fr1Mu5mxKOzY.woff2
  src/fonts/KFOmCnqEu92Fr1Mu72xKOzY.woff2
  src/fonts/KFOmCnqEu92Fr1Mu7GxKOzY.woff2
  src/fonts/KFOmCnqEu92Fr1Mu7WxKOzY.woff2
  src/fonts/KFOmCnqEu92Fr1Mu7mxKOzY.woff2
  src/fonts/fonts.css
  src/index.html
Labels: is: enhancement, DEPENDENCIES/DISTRIBUTION

#604 Added weekly (Tuesday) Build and Push Docker image + Added second fix-script
  .github/workflows/docker.yml
  Dockerfile
  backend/fix-scripts/001-fix_download_permissions.sh
  backend/fix-scripts/002-fix_dupes_per_archive_file.sh
  backend/pm2.config.js
Labels: is: enhancement, DEPENDENCIES/DISTRIBUTION, meta: update docs

#659 Remove releases folder from root dir -> fixes #625
  releases/youtubedl-material-latest.zip
Labels: is: enhancement, DEPENDENCIES/DISTRIBUTION

#683 fix: #682 install tzdata
  Dockerfile
Labels: is: bug, DEPENDENCIES/DISTRIBUTION

#687 Add permissions for tasks manager
  backend/app.js
  backend/authentication/auth.js
  backend/consts.js
  backend/utils.js
  src/app/app.component.html
  src/app/components/manage-role/manage-role.component.ts
  src/app/posts.services.ts
  src/assets/i18n/messages.en.xlf
Labels: is: bug, AUTHENTICATION
